_G.Utils = require("utils")
require("config.options")
require("config.keymaps")
require("config.lsp")


require("plugins.catppuccin")
require("plugins.snacks")
require("plugins.ui")
require("plugins.which-key")
require("plugins.sudo")
require("plugins.osc52")
require("plugins.mini")
require("plugins.rooter")
require("plugins.formatting")
require("plugins.treesitter")
require("plugins.git")
